this
  .clearCommands()  
  .do("run", 12)
  .do("turn", "left")
  .do("run", 5)
  .do("turn", "left")
  .do("run", 3)
  .do("turn", "right")
  .do("run", 10)
  .do("turn", "left")
  .do("run", 9)
  .do("turn", "right")
  .do("run", 4)
  .do("turn", "right")
  .do("run", 12)
  .do("turn", "right")
  .do("run", 4)
  .do("turn", "left")
  .do("run", 6)
  .do("turn", "left")
  .do("run", 4)
  .do("charge")
  .do("shutdown")
  .start();