this
  .do("run", 45)
  .do("turn", "left")
  .do("run", 20)
  .do("turn", "left")
  .do("run", 10)
  .do("turn", "right")
  .do("run", 30)
  .do("turn", "left")
  .do("run", 30)
  .do("turn", "right")
  .do("run", 15)
  .do("turn", "right")
  .do("run", 45)
  .do("turn", "right")
  .do("run", 10)
  .do("turn", "left")
  .do("run", 20)
  .do("turn", "left")
  .do("run", 10)
  .do("charge")
  .do("shutdown")
  .start();